# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZQNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZQNews
  pod 'Alamofire', '~> 4.7'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Kingfisher'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Spring'
  pod 'RAMAnimatedTabBarController'

end
