# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZQNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZQNews
  pod 'Moya', '~> 11.0'
  pod 'SnapKit', '~> 4.0.0'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'Kingfisher', '4.9.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'ObjectMapper'
  pod 'Spring'
  pod 'RAMAnimatedTabBarController'

end
