# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Photoshop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Photoshop
  pod 'Moya', '~> 11.0'
  pod 'SnapKit', '~> 4.0.0'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'Kingfisher', '4.9.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Spring'
#  pod 'RAMAnimatedTabBarController' , ' 3.5.0'
  pod 'ESPullToRefresh'
  pod 'KeychainAccess'
#  pod 'YPImagePicker' 
  pod 'HandyJSON'   #,' 4.1.1'
end
